### ISSUE TITLE
Add support for "streaming" plugins

### ISSUE THREAD

**Issue by xilopaint** [swiftbar/SwiftBar#118] opened 2020-12-29 23:29 UTC
I'm trying to display data retrieved from a websocket. It works if I run my script in the Terminal but SwiftBar doesn't show anything and I can't understand why (does anyone could explain?). My script is similar to this: https://github.com/Binance-docs/Binance_Futures_python/blob/master/example/websocket/subscribeaggregatetrade.py

Maybe it's the same issue once reported in BitBar repo: https://github.com/matryer/bitbar/issues/121. If it's the case, someone seems to have found a fix in this PR: https://github.com/matryer/bitbar/pull/317.

Btw, congratulations for the excellent work on this exciting project.

**Comment by melonamin** [comment] 2020-12-30 03:12
Streaming is not supported at this moment, I'll add it later if there is a sufficient demand.

**Comment by xilopaint** [comment] 2020-12-30 10:03
> Streaming is not supported at this moment, I'll add it later if there is a sufficient demand.

And what's the technical reason for the streaming plugins don't work in the current state?

**Comment by melonamin** [comment] 2020-12-30 14:28
Currently SwiftBar expects that plugin execution is finite, i.e. plugin runs and exists with an output in stdout:
* exit with code 0 and non-empty stdout - menu bar is build from the output
* exit with code 0 and empty stdout - nothing in the menu bar
* exit with code 1 - error shown in the menu bar

More than that, plugins run on a repeatable schedule.

"Streaming" plugins are completely different in that sense - run once and update menubar based on updating output in stdout, plugin never exits, plugin output should be segmented in blocks to update the menu bar, etc.

Take a look at the code, it is quite straightforward: [ExecutablePlugin.swift](https://github.com/swiftbar/SwiftBar/blob/main/SwiftBar/Plugin/ExecutablePlugin.swift)

**Comment by melonamin** [comment] 2021-01-02 15:13
Hey @xilopaint, wanna try a test build with streaming support? [SwiftBar.zip](https://github.com/swiftbar/SwiftBar/files/5760428/SwiftBar.zip)

`~~~` separates block in output, effectively resetting the menu example plugin:

```
#!/bin/bash
#<swiftbar.type>streamable</swiftbar.type>

echo "Test 1"
echo "---"
echo "Test 2"
echo "Test 3"
sleep 3
echo "~~~"
sleep 5
echo "~~~"
echo "Test 21"
echo "---"
echo "Test 22"
echo "Test 23"
sleep 3
echo "Test 24"
echo "Test 25"
sleep 3
echo "~~~"
echo "Test 31"
echo "---"
echo "Test 32"
echo "Test 33"
sleep 3
echo "~~~"
echo "Test 41"
echo "---"
echo "Test 42"
echo "Test 43"
```

**Comment by bilal-fazlani** [comment] 2021-01-02 17:03
I am also very interested in this feature.
Will try and take a look at the build.

**Comment by xilopaint** [comment] 2021-01-02 19:27
Thanks for working on this @melonamin!

I tested the build but I still can't make it work with Python. I have these two example scripts that work exactly the same way in Terminal, but only the bash one works in SwiftBar:

bash_example.sh:
```bash
#!/bin/bash
# <swiftbar.type>streamable</swiftbar.type>

echo 'foo'
sleep 5
echo '~~~'
echo 'bar'
```

python_example.py:
```python3
#!/usr/bin/env python3
# <swiftbar.type>streamable</swiftbar.type>
import time

print('foo')
time.sleep(5)
print('~~~')
print('bar')
```

**Comment by xilopaint** [comment] 2021-01-02 21:34
Hey! I got the Python script to work. All I have to do was set the `flush` parameter in the `print()` function to `True`:

```python3
#!/usr/bin/env python3
# <swiftbar.type>streamable</swiftbar.type>

import time

print('foo', flush=True)
time.sleep(5)
print('~~~')
print('bar')
```

**Comment by bilal-fazlani** [comment] 2021-01-02 21:37
Tested on bash. Works as expected. 
Will test on scala too.

**Comment by xilopaint** [comment] 2021-01-02 23:38
@melonamin, I have an issue. If my streaming plugins work in infinity loop the normal plugins don't load in SwiftBar and I just see the `...`.

This `example.py` script prints a random integer from 0 to 9 in menu bar each 3 seconds:

```python3
#!/usr/bin/env python3
# <swiftbar.type>streamable</swiftbar.type>
import time
import random

while True:
    number = random.choice(range(10))
    print(number, flush=True)
    time.sleep(3)
    print('~~~')
```

If I have this plugin in the Plugin Folder my other scripts don't load.

**Comment by melonamin** [comment] 2021-01-03 00:01
Thanks, I see the issue and working on a solution, stay tuned.

p.s. great bug reports, very easy to handle, keep it up

**Comment by melonamin** [comment] 2021-01-03 04:23
New build  [SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/5761203/SwiftBar.app.zip)

**Comment by bilal-fazlani** [comment] 2021-01-03 15:16
It seems to be working as expected for binary plugins as well.
How does one upgrade a streaming plugin? Will it require restarting SwiftBar ?

**Comment by bilal-fazlani** [comment] 2021-01-03 15:33
Right now, when Swiftbar is already running, and I drop a streaming plugin in plugins directory, I see `...` three dots in the menu bar.

It keeps showing 3 dots until I restart SwiftBar. After that, it works fine.

**Comment by xilopaint** [comment] 2021-01-03 16:15
> New build [SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/5761203/SwiftBar.app.zip)

It fixed the issue. Btw, I keep developing my streaming plugin. If any new issue occur I will report here. At the moment I have the same question of @bilal-fazlani. The `Refresh All` command doesn't refresh streaming plugins.

**Comment by melonamin** [comment] 2021-01-03 16:32
> Right now, when Swiftbar is already running, and I drop a streaming plugin in plugins directory, I see ... three dots in the menu bar.

I can't reproduce it, works on my end 🤔 

> The Refresh All command doesn't refresh streaming plugins.

Refresh does nothing for streaming plugins, do you expect it to relaunch the script?

**Comment by bilal-fazlani** [comment] 2021-01-03 16:48
> I can't reproduce it, works on my end 🤔
> Enable-Disable cycle does the trick

I could not get it to work. I had to restart swiftbar for swiftbar to accept the plugin. 
This could be related to binary plugin.. I will check.
I will try to get back with more details. 

> Refresh does nothing for streaming plugins, do you expect it to relaunch the script?

Hmm, I don't think streaming plugins should relaunched when refreshed.. they should own when they get refreshed. Just an opinion.

**Question:**
What should swiftbar do when streaming plugin exits? Relaunch quickly? What if it keeps crashing?

**Comment by xilopaint** [comment] 2021-01-03 17:03
> Refresh does nothing for streaming plugins, do you expect it to relaunch the script?

I'm not sure, tbh. I just miss a quick way to apply my changes when developing streaming plugins. I'll start to use the enable/disable cycle.

**Comment by melonamin** [comment] 2021-01-03 19:53
> What should swiftbar do when streaming plugin exits? Relaunch quickly? What if it keeps crashing?

I think - nothing. Meaning it is plugins job to handle errors and keep running continuously. If streaming plugin fails SwiftBar will show "⚠️" and error text but will not attempt to relaunch it.

**Comment by bilal-fazlani** [comment] 2021-01-04 06:05
Ok. Makes sense

**Comment by xilopaint** [comment] 2021-01-05 14:32
Hey @melonamin, I have an issue. I'm creating a streaming plugin that uses websockets of [Binance USDT Futures API](https://binance-docs.github.io/apidocs/futures/en/#change-log). At first I used the [official Python SDK](https://github.com/Binance-docs/Binance_Futures_python) which worked with SwiftBar, but the SDK has some limitations that made me rewrite the plugin with the more powerful [UNICORN Binance WebSocket API](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api#installation-and-upgrade).

After struggling for two days I finally got the script to work in Terminal but it wasn't displaying the data in SwiftBar. Then I realized that if I added a `time.sleep(1)` above `print('~~~')` the data was displayed but it wasn't new data and I guess the delay gets bigger over time. Btw, the `time.sleep` function wasn't necessary when I used the Python SDK (maybe because the library already does it?).

After that I made some tests. One of them with the script I posted in a comment above:

```python3
#!/usr/bin/env python3
# <swiftbar.type>streamable</swiftbar.type>
import time
import random

while True:
    number = random.choice(range(10))
    print(number, flush=True)
    time.sleep(3)
    print('~~~')
```

If you remove the `time.sleep()` function of the above script SwiftBar will freeze and a lot of Python instances will be created in your system forcing you to terminate them in the Terminal or Activity Monitor.

Is it an issue with SwiftBar or some kind of sleep function is mandatory for writing streaming plugins? Is this something you can handle on SwiftBar side or should I talk to the Unicorn API maintainer?

**Comment by bilal-fazlani** [comment] 2021-01-05 15:10
```
while True:
    number = random.choice(range(10))
    print(number, flush=True)
    print('~~~')
```

if you remove the sleep, then you are iterating the loop without any delay and consuming CPU very fast. Also, you are trying to reset the plugin really fast. 
This will not work. You need a realistic test with some delay.

**Comment by melonamin** [comment] 2021-01-05 15:15
Hey @xilopaint,

> After that I made some tests. One of them with the script I posted in a comment above which contains an infinity loop:
If you remove the time.sleep(3) line of the above script SwiftBar will freeze and a lot of Python instances will be created in your system forcing you to terminate them in the Terminal or Activity Monitor.

>Is it an issue with SwiftBar or some kind of sleep function is mandatory for writing streaming plugins?

I'd echo @bilal-fazlani  ob this - infinite loop without `sleep()` will just consume all available CPU(1 core in this case) because this is exactly what you asking it to do - infinitely calculate a random number the `sleep()` is needed to simulate a stream of events.

Here is a real example with reading data from a WebSocket, I've used Gemini market data:

```python
#!/usr/bin/env /opt/homebrew/bin/python3

# <swiftbar.type>streamable</swiftbar.type>

import ssl
import websocket
import _thread as thread

def on_message(ws, message):
    print(len(message), flush=True)
    print("~~~")

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    def run(*args):
        ws.send(logon_msg)
    thread.start_new_thread(run, ())

if __name__ == "__main__":
    logon_msg = '{"type": "subscribe","subscriptions":[{"name":"l2","symbols":["BTCUSD"]}]}'
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://api.gemini.com/v2/marketdata",
                                on_message = on_message,
                                on_error = on_error,
                                on_close = on_close,
                                on_open = on_open)
    ws.on_open = on_open
    ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})
```

You'll see that menubar updates really quick, but SwiftBar consumes about 5% of CPU of 1 core, spending this mostly on UI updates....

**Comment by xilopaint** [comment] 2021-01-05 15:49
@melonamin @bilal-fazlani could you guys take a look at my real example code?

https://gist.github.com/xilopaint/292de788cf401759239fd355bf5d1c13

The data is printed by the `print_stream_data()` function. I don't have any CPU consume issue with this plugin running from Terminal and the data is properly streamed as you can see on the image below:

![Screen Shot 2021-01-05 at 12 45 37](https://user-images.githubusercontent.com/11052366/103666910-02ef0c80-4f54-11eb-9870-eee4364145ab.png)

I just get data to be displayed on SwiftBar if I put a `time.sleep()` function above line 159 but in this case I have a relevant delay in the streaming which gets bigger over time.

**Comment by bilal-fazlani** [comment] 2021-01-05 15:55
This is a shot in the dark, but isn't the menu getting reset to blank by the '~~~' in the end?

**Comment by xilopaint** [comment] 2021-01-05 15:56
I made a gif of the streaming on Terminal:

https://jmp.sh/EWkNItF

**Comment by xilopaint** [comment] 2021-01-05 15:58
> This is a shot in the dark, but isn't the menu getting reset to blank by the '~~~' in the end?

It's possible something like that is happening. How could I check this?

**Comment by melonamin** [comment] 2021-01-05 16:33
`~~~` indeed resets the menu to an "empty" state.

I suggest you to remove `print(~~~)` completely and see what happens.


`~~~` should be used to clear out menu, so it shouldn't be included in each batch at the end, move it to start of the block

**Comment by xilopaint** [comment] 2021-01-05 16:54
> `~~~` should be used to clear out menu, so it shouldn't be included in each batch at the end, move it to start of the block

Oh man, I love you so much! Moving the separator to the beginning of the block did the trick and I didn't need to use `time.sleep()`!

**Comment by melonamin** [comment] 2021-01-05 23:23
Closing this, will release as a part of 1.2.1, please report if you find odd behaviors and thank you for help in development of this feature!

**Closed** 2021-01-05 23:23 UTC
Labels: enhancement

**Comment by fenhl** [comment] 2021-01-18 11:56
Wouldn't it make more sense to have `~~~` end a block as described in the original BitBar issue, rather than start a new one? That way, plugins could signal “I'm done with the current menu layout, replace the last one with this” and avoid showing half of a menu if the user happens to click while the plugin is printing one.

**Comment by bilal-fazlani** [comment] 2021-01-18 14:26
Interesting thought

**Comment by bilal-fazlani** [comment] 2021-01-18 15:19
I think it makes sense to have it just the way it is. Because it allows creating menu - as data comes. And it can even take hours. I might want to keep appending to my menu list. 
If we don't want this, we can always keep collecting the results and dump it all at once when we are ready.

I feel it depends on what you are streaming. Steaming the entire block (menu) or streaming one item (menu) at a time. I like the freedom to be able to stream each event and be able to make a menu item of it.

**Comment by fenhl** [comment] 2021-01-18 15:23
You can still do that by printing the menu each time. The current setup on the other hand doesn't have a workaround for the partial menu issue.
